import React, { useState } from 'react';
import { useAuth } from '@clerk/clerk-react';
import { UploadCloud } from 'lucide-react';
import toast from 'react-hot-toast';

export default function ListingFileUploader({ listings, onComplete }: { listings: { id: string; title: string }[]; onComplete: () => Promise<void> }) {
  const { getToken } = useAuth(); const [listingId,setListingId]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false);
  const request=async(action:string,body:unknown)=>{const token=await getToken();const response=await fetch(`/api/marketplace?action=${action}`,{method:'POST',headers:{Authorization:`Bearer ${token||''}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error||'File upload failed.');return payload;};
  const upload=async(event:React.FormEvent)=>{event.preventDefault();if(!file||!listingId)return;setBusy(true);try{const job=await request('prepare-upload',{listingId,name:file.name,size:file.size,contentType:file.type|| (file.name.toLowerCase().endsWith('.zip')?'application/zip':'')});const response=await fetch(job.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type||'application/zip'},body:file});if(!response.ok)throw new Error('Private storage upload failed. Check bucket CORS and try again.');await request('complete-upload',{assetId:job.assetId});toast.success('Uploaded to quarantine. Scanning must clear the file before publishing.');setFile(null);await onComplete();}catch(err:any){toast.error(err.message);}finally{setBusy(false);}};
  return <section className="mx-auto mt-6 max-w-7xl rounded-2xl border border-brand-border bg-brand-surface p-5"><h3 className="flex items-center gap-2 text-lg font-bold"><UploadCloud size={20}/> Product file delivery</h3><p className="mt-2 text-xs leading-5 text-brand-text-secondary">Private PDFs, ZIPs and images up to 250 MB. Uploads return the listing to draft and stay quarantined until malware scanning clears them. Storage credentials, bucket CORS and a scanner must be configured first.</p><form onSubmit={upload} className="mt-5 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs font-bold">Listing<select required value={listingId} onChange={(event)=>setListingId(event.target.value)} className="mt-2 block h-11 w-full rounded-xl border border-brand-border bg-brand-bg px-3 text-sm"><option value="">Choose your listing</option>{listings.map((listing)=><option key={listing.id} value={listing.id}>{listing.title}</option>)}</select></label><label className="min-w-0 flex-1 text-xs font-bold">Product file<input required type="file" accept=".pdf,.zip,.png,.jpg,.jpeg,.webp" onChange={(event)=>setFile(event.target.files?.[0]||null)} className="mt-2 block w-full text-xs"/></label><button disabled={busy||!file} className="btn-primary h-11 px-4 text-sm disabled:opacity-50">{busy?'Uploading…':'Upload private file'}</button></form></section>;
}
