import React, { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@clerk/clerk-react';
import toast from 'react-hot-toast';
import { Copy, Handshake } from 'lucide-react';

type Product = { id: string; title: string; resalePolicy: string; resaleCommissionPercent: number | null; privateAccessToken?: string };
type Deal = { id: string; requested_commission_percent: number; status: string; purchase_code: string; listing_id: string; listing?: { title: string; visibility: string; private_access_token: string } };

export default function ResaleWorkspace({ products }: { products: Product[] }) {
  const { getToken, userId } = useAuth();
  const [deals,setDeals]=useState<{incoming:Deal[];outgoing:Deal[]}>({incoming:[],outgoing:[]});
  const [selected,setSelected]=useState(''); const [percent,setPercent]=useState('15'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const request=useCallback(async(action:string,body?:unknown)=>{
    const token=await getToken();
    const response=await fetch(`/api/marketplace?action=${action}`,{method:body?'POST':'GET',cache:'no-store',headers:{Authorization:`Bearer ${token||''}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
    const payload=await response.json(); if(!response.ok||!payload.success) throw new Error(payload.error||'Resale request failed.'); return payload;
  },[getToken]);
  const refresh=useCallback(async()=>{if(!userId)return;try{setDeals(await request('resale-workspace'));setError('');}catch(err:any){setError(err.message);}},[request,userId]);
  useEffect(()=>{void refresh();},[refresh]);
  const product=products.find((entry)=>entry.id===selected);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!product)return;setBusy(true);try{await request('request-resale',{listingId:product.id,percent:product.resalePolicy==='fixed_percent'?product.resaleCommissionPercent:Number(percent),privateAccessToken:product.privateAccessToken});toast.success(product.resalePolicy==='fixed_percent'?'Reseller terms accepted. Your link is ready.':'Request sent to the creator.');await refresh();}catch(err:any){toast.error(err.message);}finally{setBusy(false);}};
  const decide=async(deal:Deal,status:string)=>{setBusy(true);try{await request('decide-resale',{requestId:deal.id,status});toast.success('Resale decision saved.');await refresh();}catch(err:any){toast.error(err.message);}finally{setBusy(false);}};
  const copy=async(deal:Deal)=>{const route=deal.listing?.visibility==='private'?`/marketplace/private/${deal.listing.private_access_token}`:'/marketplace';const url=new URL(route,window.location.origin);url.searchParams.set('product',deal.listing_id);url.searchParams.set('ref',deal.purchase_code);try{await navigator.clipboard.writeText(url.toString());toast.success('Reseller purchase link copied.');}catch{toast.error('Clipboard unavailable. Try another browser.');}};
  if(!userId)return null;
  return <section className="mx-auto mt-8 max-w-7xl rounded-2xl border border-brand-border bg-brand-surface p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Handshake size={20}/> Reseller workspace</h2><p className="mt-2 text-sm text-brand-text-secondary">Creators approve commission terms. Earnings remain held during the order’s 10-hour protection window.</p>{error&&<p role="alert" className="mt-4 text-sm text-red-500">{error}</p>}
    <form onSubmit={submit} className="mt-5 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs font-bold">Choose a product<select required value={selected} onChange={(event)=>setSelected(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-brand-border bg-brand-bg px-3 text-sm"><option value="">Choose from available products</option>{products.filter((entry)=>entry.resalePolicy!=='not_allowed').map((entry)=><option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label><label className="text-xs font-bold">Commission %<input required type="number" min="1" max="80" step="0.01" disabled={product?.resalePolicy==='fixed_percent'} value={product?.resalePolicy==='fixed_percent'?product.resaleCommissionPercent||'':percent} onChange={(event)=>setPercent(event.target.value)} className="mt-2 block h-11 w-28 rounded-xl border border-brand-border bg-brand-bg px-3 text-sm"/></label><button disabled={busy||!product} className="btn-primary h-11 px-4 text-sm disabled:opacity-50">{product?.resalePolicy==='fixed_percent'?'Accept fixed terms':'Request commission'}</button></form>
    <div className="mt-7 grid gap-6 lg:grid-cols-2"><div><h3 className="font-bold">Your resale agreements</h3>{!deals.outgoing.length&&<p className="mt-3 text-sm text-brand-text-secondary">No agreements yet.</p>}{deals.outgoing.map((deal)=><article key={deal.id} className="mt-3 rounded-xl border border-brand-border p-4"><p className="text-sm font-bold">{deal.listing?.title}</p><p className="mt-1 text-xs text-brand-text-secondary">{deal.requested_commission_percent}% · {deal.status}</p>{deal.status==='approved'&&<button onClick={()=>void copy(deal)} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-brand-accent"><Copy size={14}/> Copy purchase link</button>}</article>)}</div><div><h3 className="font-bold">Requests for your products</h3>{!deals.incoming.length&&<p className="mt-3 text-sm text-brand-text-secondary">No requests yet.</p>}{deals.incoming.map((deal)=><article key={deal.id} className="mt-3 rounded-xl border border-brand-border p-4"><p className="text-sm font-bold">{deal.listing?.title}</p><p className="mt-1 text-xs text-brand-text-secondary">{deal.requested_commission_percent}% requested · {deal.status}</p><div className="mt-3 flex gap-3">{deal.status==='pending'&&<><button disabled={busy} onClick={()=>void decide(deal,'approved')} className="text-xs font-bold text-brand-accent">Approve {deal.requested_commission_percent}%</button><button disabled={busy} onClick={()=>void decide(deal,'rejected')} className="text-xs font-bold text-red-500">Reject</button></>}{deal.status==='approved'&&<button disabled={busy} onClick={()=>void decide(deal,'revoked')} className="text-xs font-bold text-red-500">Revoke future commissions</button>}</div></article>)}</div></div>
  </section>;
}
