import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import { Link } from "react-router-dom";
import { ArrowLeft, CheckCircle2, FileWarning, Loader2, XCircle } from "lucide-react";
import toast from "react-hot-toast";

export default function AdminMarketplaceFiles() {
  const { getToken } = useAuth();
  const [assets, setAssets] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const request = useCallback(async (action: string, body?: unknown) => { const token = await getToken(); const response = await fetch(`/api/marketplace?action=${action}`, { method: body ? "POST" : "GET", headers: { Authorization: `Bearer ${token || ""}`, "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined, cache: "no-store" }); const payload = await response.json().catch(() => null); if (!response.ok || !payload?.success) throw new Error(payload?.error || "Marketplace request failed."); return payload; }, [getToken]);
  const load = useCallback(async () => { setLoading(true); try { const payload = await request("admin-workspace"); setAssets((payload.assets || []).filter((asset: any) => asset.status === "quarantined")); } catch (error: any) { toast.error(error.message || "Could not load uploaded files."); } finally { setLoading(false); } }, [request]);
  useEffect(() => { void load(); }, [load]);
  const review = async (assetId: string, outcome: "clean" | "rejected") => { if (!window.confirm(outcome === "clean" ? "Approve this file only after you have inspected it in your private storage. Continue?" : "Reject this uploaded file?")) return; setBusy(assetId); try { await request("review-asset", { assetId, outcome }); toast.success(outcome === "clean" ? "File approved. The seller can publish the product now." : "File rejected."); await load(); } catch (error: any) { toast.error(error.message || "Review could not be saved."); } finally { setBusy(null); } };
  return <main className="min-h-screen bg-brand-bg px-4 pb-20 pt-24 text-brand-text sm:px-6"><div className="mx-auto max-w-4xl"><Link to="/admin/marketplace" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-text-secondary"><ArrowLeft size={16} /> Marketplace control centre</Link><header className="mt-6 rounded-3xl border border-brand-border bg-brand-surface p-7"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-500/10 text-amber-500"><FileWarning size={22} /></span><h1 className="mt-5 text-3xl font-black">Product file security review</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-brand-text-secondary">Files remain private until an admin has inspected them in the secure storage bucket and approves or rejects them. This keeps unsafe downloads out of the marketplace.</p></header><section className="mt-6 space-y-3">{loading ? <div className="grid h-48 place-items-center"><Loader2 className="animate-spin text-brand-accent" /></div> : assets.length ? assets.map((asset) => <article key={asset.id} className="flex flex-col gap-4 rounded-2xl border border-brand-border bg-brand-surface p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h2 className="truncate font-black">{asset.original_name}</h2><p className="mt-1 text-xs text-brand-text-secondary">{asset.content_type} · {Math.ceil(Number(asset.actual_size || asset.expected_size || 0) / 1024 / 1024)} MB · awaiting review</p><p className="mt-1 text-[10px] text-brand-text-secondary">Seller: {asset.seller_id}</p></div><div className="flex gap-2"><button disabled={busy === asset.id} onClick={() => void review(asset.id, "rejected")} className="flex h-10 items-center gap-2 rounded-xl border border-red-500/30 px-4 text-xs font-black text-red-500"><XCircle size={14} /> Reject</button><button disabled={busy === asset.id} onClick={() => void review(asset.id, "clean")} className="btn-primary flex h-10 items-center gap-2 px-4 text-xs font-black"><CheckCircle2 size={14} /> Approve</button></div></article>) : <div className="rounded-3xl border border-dashed border-brand-border bg-brand-surface p-12 text-center"><CheckCircle2 className="mx-auto text-emerald-500" size={36} /><h2 className="mt-4 text-xl font-black">Nothing waiting for review</h2><p className="mt-2 text-sm text-brand-text-secondary">New direct-file uploads will appear here.</p></div>}</section></div></main>;
}
