import React from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import MarketplaceCookieConsent from '../components/marketplace/MarketplaceCookieConsent';

const sections = [
  ['Seller eligibility', 'Public sellers must be at least 18 years old, provide accurate account information, hold an active seller plan and complete identity verification. Private product links do not represent identity approval or public Marketplace endorsement.'],
  ['Buyer protection', 'Marketplace payments are protected for 10 hours. A buyer must report a genuine product issue during that window. Plugsy reviews reports and may refund the buyer and revoke access when the product is unavailable, misleading or materially different from its description.'],
  ['Seller payouts', 'After the 10-hour protection period without an open report, seller funds move to Processing Payout. They become available in the seller’s Plugsy Wallet at 11:00 AM on the next business day. If the protection period ends before 11:00 AM on a business day, payout is available at 11:00 AM that same day. Weekend payouts are processed on Monday.'],
  ['Digital delivery', 'Products are delivered to the buyer’s signed-in Plugsy library. Buyers must not redistribute files unless the listing expressly permits resale. Download links may expire and can be regenerated only for an entitled account.'],
  ['Seller responsibilities', 'Sellers must own or have permission to sell every file, describe products accurately, provide safe files, and complete identity verification before public publishing. Fraud, malware, copyright abuse and deceptive listings may lead to removal and frozen funds.'],
  ['Refunds and disputes', 'Digital purchases are not automatically refundable after successful delivery. During the protection window, buyers can submit one truthful report with details. Plugsy may request evidence and its recorded decision controls the held marketplace funds.'],
  ['Marketplace fees', 'Private product links can be created without a public publishing fee. Public marketplace publishing requires an active monthly or yearly seller plan. The applicable plan price, transaction fee and reseller commission are shown before confirmation.'],
  ['Identity and privacy', 'Public sellers choose either BVN + Face Validation or NIN + Face Validation, processed by Prembly after explicit consent. Plugsy stores the verification result, provider session reference, consent-policy version and timestamps—not the BVN, NIN, selfie or biometric response. Verification is used only for seller eligibility, fraud prevention and marketplace safety. A failed automated result may be challenged through Plugsy Support for human review.'],
  ['Cookies and ad measurement', 'Essential storage keeps sign-in state, security preferences and retry identifiers that prevent duplicate charges. Optional analytics and seller ad measurement are separate choices. If you opt in to ad measurement, Meta/TikTok pixels may receive product-view and checkout events for that seller’s products; a confirmed purchase is also sent server-side when that seller has connected an Events API token. Purchase signals are sent only after Plugsy confirms payment, use an order reference for deduplication, and do not include BVN, NIN, selfie or biometric data. You can review or withdraw your optional choice at any time using Cookie settings.'],
  ['Account safety', 'Never share passwords, one-time codes or private product files. Plugsy may pause suspicious listings, purchases, withdrawals or seller access while reviewing fraud, sanctions, account takeover or payment risk.'],
];

export default function MarketplacePolicy() {
  return <main className="min-h-screen bg-brand-bg px-4 pb-28 pt-24 text-brand-text sm:px-6"><Helmet><title>Marketplace policy | Plugsy</title><meta name="description" content="Plugsy Marketplace buyer protection, seller, privacy and cookie policy."/></Helmet><div className="mx-auto max-w-4xl"><Link to="/marketplace" className="inline-flex items-center gap-2 text-sm text-brand-text-secondary"><ArrowLeft size={16}/> Marketplace</Link><header className="mt-6 rounded-[2rem] border border-brand-border bg-brand-surface p-7 sm:p-10"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-accent/10 text-brand-accent"><ShieldCheck/></span><p className="mt-6 text-[10px] font-black uppercase tracking-[.22em] text-brand-accent">Marketplace terms · version 2</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Clear rules for buying and selling.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-brand-text-secondary">Effective 2 October 2026. This marketplace-specific policy supplements Plugsy’s general terms and privacy policy. Users must accept the applicable terms before a paid action or identity verification.</p></header><div className="mt-6 grid gap-4 md:grid-cols-2">{sections.map(([title, body]) => <section key={title} className="rounded-2xl border border-brand-border bg-brand-surface p-6"><h2 className="font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-brand-text-secondary">{body}</p></section>)}</div><p className="mt-6 rounded-2xl border border-brand-border bg-brand-surface p-5 text-sm leading-6 text-brand-text-secondary">Questions, access requests, consent withdrawal requests and verification appeals can be submitted through Plugsy Support. Withdrawing consent does not invalidate processing already completed lawfully and may prevent public selling where identity verification is required for marketplace safety.</p></div><MarketplaceCookieConsent/></main>;
}
