import React from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import MarketplaceCookieConsent from '../components/marketplace/MarketplaceCookieConsent';

const sections = [
  ['Buyer protection', 'Marketplace payments are held for 10 hours. A buyer must report a genuine product issue during that window. Plugsy reviews reports and may refund the buyer and revoke access when the product is unavailable, misleading or materially different from its description.'],
  ['Digital delivery', 'Products are delivered to the buyer’s signed-in Plugsy library. Buyers must not redistribute files unless the listing expressly permits resale. Download links may expire and can be regenerated only for an entitled account.'],
  ['Seller responsibilities', 'Sellers must own or have permission to sell every file, describe products accurately, provide safe files, and complete identity verification before public publishing. Fraud, malware, copyright abuse and deceptive listings may lead to removal and frozen funds.'],
  ['Refunds and disputes', 'Digital purchases are not automatically refundable after successful delivery. During the protection window, buyers can submit one truthful report with details. Plugsy may request evidence and its recorded decision controls the held marketplace funds.'],
  ['Marketplace fees', 'Private product links can be created without a public publishing fee. Public marketplace publishing requires an active seller plan, currently ₦1,500 per month. Transaction and reseller commission amounts are shown before confirmation.'],
  ['Identity and privacy', 'Seller identity checks are handled through Dojah. Plugsy stores the verification reference and result status, not identity-document images in this integration. Dojah processes submitted identity and selfie data under its own privacy terms.'],
  ['Cookies and local storage', 'Essential storage keeps sign-in state, security preferences, cookie choices and retry identifiers that prevent duplicate charges. Optional analytics is used only after consent. You can clear your browser storage to reset your choice.'],
  ['Account safety', 'Never share passwords, one-time codes or private product files. Plugsy may pause suspicious listings, purchases, withdrawals or seller access while reviewing fraud, sanctions, account takeover or payment risk.'],
];

export default function MarketplacePolicy() {
  return <main className="min-h-screen bg-brand-bg px-4 pb-28 pt-24 text-brand-text sm:px-6"><Helmet><title>Marketplace policy | Plugsy</title><meta name="description" content="Plugsy Marketplace buyer protection, seller, privacy and cookie policy."/></Helmet><div className="mx-auto max-w-4xl"><Link to="/marketplace" className="inline-flex items-center gap-2 text-sm text-brand-text-secondary"><ArrowLeft size={16}/> Marketplace</Link><header className="mt-6 rounded-[2rem] border border-brand-border bg-brand-surface p-7 sm:p-10"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-accent/10 text-brand-accent"><ShieldCheck/></span><p className="mt-6 text-[10px] font-black uppercase tracking-[.22em] text-brand-accent">Marketplace terms · version 1</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Clear rules for buying and selling.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-brand-text-secondary">Effective 15 September 2026. This marketplace-specific policy supplements Plugsy’s general terms and privacy policy. Users must accept the applicable terms before a paid action.</p></header><div className="mt-6 grid gap-4 md:grid-cols-2">{sections.map(([title, body]) => <section key={title} className="rounded-2xl border border-brand-border bg-brand-surface p-6"><h2 className="font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-brand-text-secondary">{body}</p></section>)}</div><p className="mt-6 rounded-2xl border border-amber-500/25 bg-amber-500/10 p-5 text-sm leading-6">Public payments remain disabled during preview. Before launch, these terms should be reviewed by a Nigerian-qualified lawyer and linked to the final privacy, refund and prohibited-products policies.</p></div><MarketplaceCookieConsent/></main>;
}
