import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import { Link, useNavigate } from "react-router-dom";
import { AnimatePresence, motion } from "motion/react";
import { ArrowLeft, BarChart3, Box, CheckCircle2, Clock3, Copy, Loader2, MessageCircle, PackagePlus, Plus, ShoppingBag, Store, WalletCards, X } from "lucide-react";
import toast from "react-hot-toast";
import ListingFileUploader from "../components/marketplace/ListingFileUploader";
import SellerPremiumPlan from "../components/marketplace/SellerPremiumPlan";
import SellerVerification from "../components/marketplace/SellerVerification";

const money = (value: number) => `₦${Number(value || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`;
const blank = { title:"", summary:"", description:"", category:"templates", price:"", coverImageUrl:"", deliveryUrl:"", deliveryLabel:"Open product", visibility:"private", resalePolicy:"not_allowed", resaleCommissionPercent:"" };

export default function SellerDashboard() {
  const { getToken } = useAuth();
  const navigate = useNavigate();
  const [workspace,setWorkspace]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState("");
  const [period,setPeriod]=useState(30); const [tab,setTab]=useState<"overview"|"products"|"customers">("overview");
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>(blank);
  const request=useCallback(async(action:string,options:RequestInit={})=>{const token=await getToken();const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${token||""}`);headers.set("Accept","application/json");if(options.body)headers.set("Content-Type","application/json");const response=await fetch(`/api/marketplace?action=${action}`,{...options,headers});const payload=await response.json().catch(()=>null);if(!response.ok||!payload?.success)throw new Error(payload?.error||"Marketplace request failed.");return payload;},[getToken]);
  const load=useCallback(async()=>{try{const data=await request("workspace");setWorkspace(data);}catch(e:any){toast.error(e.message);}finally{setLoading(false);}},[request]);
  useEffect(()=>{void load();},[load]);
  const sales=useMemo(()=>{const floor=Date.now()-period*86400000;return (workspace?.sales||[]).filter((sale:any)=>new Date(sale.created_at).getTime()>=floor);},[workspace,period]);
  const metrics=useMemo(()=>({gross:sales.reduce((n:number,s:any)=>n+Number(s.amount||0),0),net:sales.reduce((n:number,s:any)=>n+Number(s.seller_amount||0),0),held:sales.filter((s:any)=>s.funds_status==="held").reduce((n:number,s:any)=>n+Number(s.seller_amount||0),0),released:sales.filter((s:any)=>s.funds_status==="released").reduce((n:number,s:any)=>n+Number(s.seller_amount||0),0),buyers:new Set(sales.map((s:any)=>s.buyer_id)).size}),[sales]);
  const daily=useMemo(()=>{const rows:Array<{label:string,value:number}>=[];const days=Math.min(period,30);for(let i=days-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);rows.push({label:d.toLocaleDateString("en-NG",{month:"short",day:"numeric"}),value:sales.filter((s:any)=>String(s.created_at).slice(0,10)===key).reduce((n:number,s:any)=>n+Number(s.amount||0),0)});}return rows;},[sales,period]);
  const max=Math.max(...daily.map(d=>d.value),1);
  const productStats=useMemo(()=>Object.values(sales.reduce((map:any,sale:any)=>{const key=sale.listing_id;map[key]||={id:key,title:sale.product_title,orders:0,revenue:0};map[key].orders+=1;map[key].revenue+=Number(sale.amount||0);return map;},{})).sort((a:any,b:any)=>b.revenue-a.revenue).slice(0,5) as any[],[sales]);
  const edit=(listing:any)=>{setEditing(listing);setForm({title:listing.title,summary:listing.summary||"",description:listing.description||"",category:listing.category,price:String(listing.price),coverImageUrl:listing.cover_image_url||"",deliveryUrl:listing.delivery_url||"",deliveryLabel:listing.delivery_label||"Open product",visibility:listing.visibility,resalePolicy:listing.resale_policy,resaleCommissionPercent:listing.resale_commission_percent==null?"":String(listing.resale_commission_percent)});setOpen(true);};
  const close=()=>{setOpen(false);setEditing(null);setForm(blank);};
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy("save");try{await request(editing?"update-listing":"create-listing",{method:editing?"PATCH":"POST",body:JSON.stringify({...form,listingId:editing?.id})});toast.success(editing?"Draft updated.":"Your first product draft is ready.");close();await load();setTab("products");}catch(err:any){toast.error(err.message);}finally{setBusy("");}};
  const status=async(listing:any,next:string)=>{setBusy(listing.id);try{await request("publish",{method:"POST",body:JSON.stringify({listingId:listing.id,status:next})});toast.success(`Product ${next}.`);await load();}catch(err:any){toast.error(err.message);}finally{setBusy("");}};
  if(loading)return <main className="flex min-h-screen items-center justify-center bg-brand-bg text-brand-text"><Loader2 className="animate-spin text-brand-accent"/></main>;
  const listings=workspace?.listings||[];
  return <main className="min-h-screen bg-brand-bg px-4 pb-28 pt-24 text-brand-text sm:px-7">
    <div className="mx-auto max-w-7xl">
      <header className="overflow-hidden rounded-[28px] border border-brand-border bg-brand-surface p-5 shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><Link to="/marketplace" className="inline-flex items-center gap-2 text-xs font-bold text-brand-text-secondary"><ArrowLeft size={15}/> Marketplace</Link><div className="mt-5 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-accent text-white"><Store/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-brand-accent">Seller workspace</p><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Run your store</h1></div></div><p className="mt-3 max-w-xl text-sm text-brand-text-secondary">Products, orders and customers in one private workspace. Only you can access this page.</p></div><button onClick={()=>setOpen(true)} className="btn-primary flex h-12 items-center justify-center gap-2 px-5 text-sm font-black"><Plus size={17}/> Create product</button></div></header>
      <nav className="mt-5 flex gap-2 overflow-x-auto rounded-2xl border border-brand-border bg-brand-surface p-1.5">{[["overview","Overview",BarChart3],["products","Products",Box],["customers","Customers",ShoppingBag]].map(([key,label,Icon]:any)=><button key={key} onClick={()=>setTab(key)} className={`flex min-w-fit items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black transition ${tab===key?"bg-brand-text text-brand-surface":"text-brand-text-secondary hover:bg-brand-bg"}`}><Icon size={15}/>{label}</button>)}</nav>
      {tab==="overview"&&<SellerInsights products={productStats} released={metrics.released} held={metrics.held}/>} 
      {tab==="overview"&&<><div className="mt-6 flex justify-end"><select value={period} onChange={e=>setPeriod(Number(e.target.value))} className="h-10 rounded-xl border border-brand-border bg-brand-surface px-3 text-xs font-bold"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></div><section className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Gross sales",money(metrics.gross),ShoppingBag],["Your earnings",money(metrics.net),CheckCircle2],["Funds on hold",money(metrics.held),Clock3],["Unique buyers",metrics.buyers,MessageCircle]].map(([label,value,Icon]:any)=><article key={label} className="rounded-2xl border border-brand-border bg-brand-surface p-5 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-accent/10 text-brand-accent"><Icon size={18}/></span><p className="mt-5 text-xs font-bold text-brand-text-secondary">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>)}</section><section className="mt-4 rounded-3xl border border-brand-border bg-brand-surface p-5 sm:p-7"><div className="flex items-end justify-between"><div><h2 className="text-xl font-black">Sales volume</h2><p className="text-xs text-brand-text-secondary">Successful marketplace orders in this period</p></div><strong>{money(metrics.gross)}</strong></div><div className="mt-8 flex h-48 items-end gap-1.5 overflow-hidden">{daily.map((point,i)=><div key={i} title={`${point.label}: ${money(point.value)}`} className="group flex min-w-0 flex-1 flex-col items-center justify-end"><motion.div initial={{height:0}} animate={{height:`${Math.max(point.value/max*100,point.value?5:1)}%`}} className="w-full max-w-8 rounded-t-md bg-brand-accent/75 transition group-hover:bg-brand-accent"/><span className="mt-2 hidden text-[8px] text-brand-text-secondary sm:block">{i%(daily.length>14?5:2)===0?point.label:""}</span></div>)}</div>{!sales.length&&<p className="-mt-28 text-center text-sm text-brand-text-secondary">No sales in this period yet.</p>}</section></>}
      {tab==="products"&&<section className="mt-6"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-2xl font-black">Products</h2><p className="text-sm text-brand-text-secondary">Create privately for free, or publish publicly after verification.</p></div><span className="text-sm font-bold">{listings.length} total</span></div>{!listings.length?<Empty onCreate={()=>setOpen(true)}/>:<div className="grid gap-4 lg:grid-cols-2">{listings.map((item:any)=><article key={item.id} className="rounded-2xl border border-brand-border bg-brand-surface p-5"><div className="flex items-start justify-between gap-4"><div><span className="text-[9px] font-black uppercase tracking-wider text-brand-accent">{item.status} · {item.visibility}</span><h3 className="mt-2 text-lg font-black">{item.title}</h3><p className="mt-1 text-sm text-brand-text-secondary">{money(item.price)} · {item.category.replace(/_/g," ")}</p></div><button onClick={()=>edit(item)} className="rounded-xl border border-brand-border px-3 py-2 text-xs font-bold">Edit</button></div><div className="mt-5 flex flex-wrap gap-2">{item.status!=="published"&&<button disabled={busy===item.id} onClick={()=>void status(item,"published")} className="btn-primary h-9 px-3 text-xs">Publish</button>}{item.status==="published"&&<button disabled={busy===item.id} onClick={()=>void status(item,"paused")} className="h-9 rounded-xl border border-brand-border px-3 text-xs font-bold">Pause</button>}<button onClick={()=>{const url=item.visibility==="private"?`${location.origin}/marketplace/private/${item.private_access_token}`:`${location.origin}/marketplace?product=${item.id}`;void navigator.clipboard.writeText(url);toast.success("Product link copied.");}} className="flex h-9 items-center gap-1 rounded-xl border border-brand-border px-3 text-xs font-bold"><Copy size={13}/> Copy link</button></div></article>)}</div>}<ListingFileUploader listings={listings} onComplete={load}/><SellerVerification seller={workspace?.seller} onComplete={load}/><SellerPremiumPlan seller={workspace?.seller} onComplete={load}/></section>}
      {tab==="customers"&&<section className="mt-6 overflow-hidden rounded-3xl border border-brand-border bg-brand-surface"><div className="border-b border-brand-border p-5 sm:p-7"><h2 className="text-2xl font-black">Customers & orders</h2><p className="text-sm text-brand-text-secondary">Every buyer shown here is tied to one of your verified orders.</p></div>{sales.length?sales.map((sale:any)=><div key={sale.id} className="flex flex-col gap-4 border-b border-brand-border p-5 last:border-0 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3">{sale.buyer?.avatar?<img src={sale.buyer.avatar} className="h-10 w-10 rounded-full object-cover" alt=""/>:<span className="grid h-10 w-10 place-items-center rounded-full bg-brand-accent/10 font-black text-brand-accent">{sale.buyer?.name?.[0]||"P"}</span>}<div><p className="font-bold">{sale.buyer?.name||"Plugsy buyer"}</p><p className="text-xs text-brand-text-secondary">{sale.product_title} · {new Date(sale.created_at).toLocaleDateString()}</p></div></div><div><p className="font-black">{money(sale.amount)}</p><p className="text-[10px] uppercase text-brand-text-secondary">{sale.funds_status}</p></div><button onClick={()=>navigate(`/chats?start=${encodeURIComponent(sale.buyer_id)}`)} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-brand-border px-4 text-xs font-black"><MessageCircle size={15}/> Message</button></div>):<p className="p-12 text-center text-sm text-brand-text-secondary">No customer orders in this period.</p>}</section>}
    </div>
    <AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[10000] flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-6"><form onSubmit={save} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl border border-brand-border bg-brand-bg p-6 sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-black uppercase text-brand-accent">{editing?"Edit draft":"New product"}</p><h2 className="mt-1 text-2xl font-black">Product details</h2></div><button type="button" onClick={close}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Title"><input required minLength={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Price (₦)"><input required type="number" min="100" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field><Field label="Category"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["templates","courses","design","video","social_media","business","creator_tools"].map(x=><option key={x} value={x}>{x.replace(/_/g," ")}</option>)}</select></Field><Field label="Visibility"><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="private">Private link — free</option><option value="public">Public marketplace</option></select></Field><div className="sm:col-span-2"><Field label="Summary"><input value={form.summary} maxLength={220} onChange={e=>setForm({...form,summary:e.target.value})}/></Field></div><div className="sm:col-span-2"><Field label="Description"><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div><div className="sm:col-span-2"><Field label="Secure delivery URL"><input type="url" value={form.deliveryUrl} onChange={e=>setForm({...form,deliveryUrl:e.target.value})} placeholder="https://... (or upload a file after saving)"/></Field></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="h-11 rounded-xl border border-brand-border px-5">Cancel</button><button disabled={busy==="save"} className="btn-primary h-11 px-5">{busy==="save"?"Saving…":"Save draft"}</button></div></form></motion.div>}</AnimatePresence>
    <style>{`.seller-field input,.seller-field select,.seller-field textarea{width:100%;border:1px solid var(--brand-border,rgba(128,128,128,.3));border-radius:12px;background:var(--brand-surface,transparent);padding:12px 14px;outline:none}.seller-field input:focus,.seller-field select:focus,.seller-field textarea:focus{border-color:var(--brand-accent,#1677ff)}`}</style>
  </main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="seller-field block text-xs font-bold text-brand-text-secondary"><span className="mb-2 block uppercase tracking-wider">{label}</span>{children}</label>}
function Empty({onCreate}:{onCreate:()=>void}){return <div className="rounded-3xl border border-dashed border-brand-border bg-brand-surface p-12 text-center"><PackagePlus className="mx-auto text-brand-accent" size={36}/><h3 className="mt-4 text-xl font-black">Create your first product</h3><p className="mt-2 text-sm text-brand-text-secondary">Your seller dashboard becomes active as soon as the first draft is saved.</p><button onClick={onCreate} className="btn-primary mt-5 h-11 px-5">Create product</button></div>}
function SellerInsights({products,released,held}:{products:any[];released:number;held:number}){return <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border border-brand-border bg-brand-surface p-5 sm:p-7"><h2 className="text-lg font-black">Top products</h2><p className="text-xs text-brand-text-secondary">Performance updates with the selected period</p><div className="mt-5 space-y-4">{products.length?products.map((product,index)=><div key={product.id} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-bg text-xs font-black">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.title}</p><p className="text-[10px] text-brand-text-secondary">{product.orders} order{product.orders===1?"":"s"}</p></div><strong className="text-sm">{money(product.revenue)}</strong></div>):<p className="py-8 text-center text-sm text-brand-text-secondary">Product performance appears after your first sale.</p>}</div></section><section className="rounded-3xl border border-brand-border bg-brand-surface p-5 sm:p-7"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-500"><WalletCards size={20}/></span><h2 className="mt-4 text-lg font-black">Money status</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-brand-bg p-4"><p className="text-[10px] font-bold text-brand-text-secondary">RELEASED</p><p className="mt-1 text-xl font-black">{money(released)}</p></div><div className="rounded-2xl bg-brand-bg p-4"><p className="text-[10px] font-bold text-brand-text-secondary">PROTECTED HOLD</p><p className="mt-1 text-xl font-black">{money(held)}</p></div></div><p className="mt-4 text-xs leading-5 text-brand-text-secondary">Marketplace earnings stay protected for 10 hours. Cleared funds move to your Plugsy Wallet automatically.</p></section></div>}
