export const CATEGORY_CONFIG: Record<string, any> = {
  graphic_design: {
    name: "Graphic Design",
    price: 1200,
    slug: "graphic_design",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 0,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    description: "Brand identities, print, digital design",
  },
  video_editing: {
    name: "Video Editing",
    price: 1500,
    slug: "video_editing",
    maxImages: 0,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: false,
    imageInWorkFeed: false,
    showVideoComingSoon: true,
    description: "Cuts, transitions, color grades, motion work",
    note: "Only avatar and cover photo allowed as images",
  },
  motion_graphics: {
    name: "Motion Graphics",
    price: 1500,
    slug: "motion_graphics",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Animations, effects, Kinetic type, UI motion",
  },
  web_development: {
    name: "Web Development",
    price: 1200,
    slug: "web_development",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    allowProjectLinks: true,
    description: "Sites, apps, and digital experiences",
  },
  uiux_design: {
    name: "UI/UX Design",
    price: 1450,
    slug: "uiux_design",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 0,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    description: "User interfaces and experience design",
  },
  copywriting: {
    name: "Copywriting",
    price: 1400,
    slug: "copywriting",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    pdfEnabled: false,
    showVideoComingSoon: false,
    allowProjectLinks: true,
    description: "Words that convert and captivate",
  },
  content_writing: {
    name: "Content Writing",
    price: 1400,
    slug: "content_writing",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    pdfEnabled: false,
    showVideoComingSoon: false,
    allowProjectLinks: true,
    description: "Articles, blogs, scripts, and long-form literature",
  },
  digital_marketing: {
    name: "Digital Marketing",
    price: 1000,
    slug: "digital_marketing",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 0,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    description: "Growth, campaigns, ads, analytics, and strategy",
  },
  social_media_management: {
    name: "Social Media Management",
    price: 1000,
    slug: "social_media_management",
    maxImages: 20,
    maxVideos: 0,
    maxLinks: 0,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    description: "Community management, grid planning, posting schedules",
  },
  photography: {
    name: "Photography",
    price: 2400,
    slug: "photography",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Visual storytelling through the lens",
  },
  videography: {
    name: "Videography",
    price: 2400,
    slug: "videography",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Filming, camera operating, video production",
  },
  ai_automation: {
    name: "AI Automation",
    price: 2200,
    slug: "ai_automation",
    maxImages: 15,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Building autonomous agents, workflows, and integrations",
  },
  prompt_engineering: {
    name: "Prompt Engineering",
    price: 2200,
    slug: "prompt_engineering",
    maxImages: 15,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description:
      "Optimizing AI queries, context tuning, and prompt architecture",
  },
  cybersecurity: {
    name: "Cybersecurity",
    price: 1800,
    slug: "cybersecurity",
    maxImages: 15,
    maxVideos: 0,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: false,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: false,
    description: "Security analysis and auditing",
  },
  three_d_animation: {
    name: "3D Animation",
    price: 1500,
    slug: "three_d_animation",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "3D model compositions and CGI animations",
  },
  vfx: {
    name: "VFX",
    price: 1500,
    slug: "vfx",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Visual effect integrations",
  },
  three_d_design: {
    name: "3D Animation & VFX",
    price: 2400,
    slug: "three_d_design",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: false,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    showVideoComingSoon: true,
    description: "Dimensional worlds and effects",
  },
};

export const getCategoryConfig = (slug: string) => {
  try {
    const parsed = JSON.parse(slug);
    if (Array.isArray(parsed) && parsed.length > 0) {
      const configs = parsed
        .map((s) => CATEGORY_CONFIG[s as keyof typeof CATEGORY_CONFIG])
        .filter(Boolean);
      if (configs.length === 0) return null;
      if (configs.length === 1) return configs[0];

      const mergedName = configs.map((c) => c.name).join(" & ");
      const maxPrice = Math.max(...configs.map((c) => c.price));

      return configs.reduce(
        (acc, curr) => ({
          name: mergedName,
          price: maxPrice,
          slug: parsed.join("_"),
          maxImages: Math.max(acc.maxImages, curr.maxImages),
          maxVideos: Math.max(acc.maxVideos, curr.maxVideos),
          maxLinks: Math.max(acc.maxLinks, curr.maxLinks),
          maxPDFs: Math.max(acc.maxPDFs || 0, curr.maxPDFs || 0),
          videoUploadEnabled: acc.videoUploadEnabled || curr.videoUploadEnabled,
          videoEmbedEnabled: acc.videoEmbedEnabled || curr.videoEmbedEnabled,
          imageEnabled: acc.imageEnabled || curr.imageEnabled,
          imageInWorkFeed: acc.imageInWorkFeed || curr.imageInWorkFeed,
          pdfEnabled: acc.pdfEnabled || curr.pdfEnabled,
          showVideoComingSoon:
            acc.showVideoComingSoon && curr.showVideoComingSoon,
          description: "Multi-disciplinary portfolio",
        }),
        { ...configs[0] },
      );
    }
  } catch (e) {
    // not JSON
  }

  return CATEGORY_CONFIG[slug as keyof typeof CATEGORY_CONFIG] || {
    name: "General Portfolio",
    price: 1000,
    slug: "general",
    maxImages: 20,
    maxVideos: 20,
    maxLinks: 20,
    maxPDFs: 0,
    videoUploadEnabled: true,
    videoEmbedEnabled: true,
    imageEnabled: true,
    imageInWorkFeed: true,
    pdfEnabled: false,
    showVideoComingSoon: false,
    description: "General portfolio",
  };
};
